spring.application.name=stock-market
spring.jackson.property-naming-strategy=SNAKE_CASE
spring.datasource.url=jdbc:postgresql://db:5432/stock_market
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=stock_user
spring.datasource.password=stock_pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
